package plugin

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log/slog"
	"net"
	"net/http"
	"sync"
	"time"

	"github.com/rbaliyan/mailbox"
	mbxstore "github.com/rbaliyan/mailbox/store"
)

// CrowdSecConfig configures the CrowdSec bouncer plugin.
//
// The plugin queries the CrowdSec Local API (LAPI) to check whether the
// sending IP has an active "ban" decision. The LAPI is typically a local
// sidecar running on the same host as postbox.
//
// Decisions are cached locally for CacheTTL to avoid hammering the LAPI on
// every incoming message.
type CrowdSecConfig struct {
	// Endpoint is the CrowdSec LAPI base URL. Default "http://localhost:8080".
	Endpoint string
	// APIKey is the bouncer API key generated by `cscli bouncers add`.
	APIKey string
	// Timeout is the HTTP call timeout. Default 2s.
	Timeout time.Duration
	// FailOpen allows messages through when the LAPI is unreachable or returns
	// an unexpected error. Default true (fail open = prefer availability).
	FailOpen bool
	// CacheTTL is how long a decision (ban or clean) is cached. Default 30s.
	CacheTTL time.Duration
}

type crowdSecDecision struct {
	banned  bool
	expires time.Time
}

// CrowdSecPlugin is a mailbox.SendHook that rejects messages from IPs that
// have an active ban decision in CrowdSec. The connecting IP is read from the
// X-SMTP-Remote-Addr internal header injected by the SMTP server.
type CrowdSecPlugin struct {
	name   string
	cfg    CrowdSecConfig
	client *http.Client
	logger *slog.Logger

	mu    sync.Mutex
	cache map[string]crowdSecDecision // key: IP string
}

// CrowdSecOption configures a CrowdSecPlugin.
type CrowdSecOption func(*CrowdSecPlugin)

// WithCrowdSecLogger sets the structured logger.
func WithCrowdSecLogger(l *slog.Logger) CrowdSecOption {
	return func(p *CrowdSecPlugin) { p.logger = l }
}

// NewCrowdSec creates a CrowdSecPlugin.
func NewCrowdSec(name string, cfg CrowdSecConfig, opts ...CrowdSecOption) *CrowdSecPlugin {
	if cfg.Endpoint == "" {
		cfg.Endpoint = "http://localhost:8080"
	}
	if cfg.Timeout == 0 {
		cfg.Timeout = 2 * time.Second
	}
	if cfg.CacheTTL == 0 {
		cfg.CacheTTL = 30 * time.Second
	}
	p := &CrowdSecPlugin{
		name:   name,
		cfg:    cfg,
		client: &http.Client{Timeout: cfg.Timeout},
		logger: slog.Default(),
		cache:  make(map[string]crowdSecDecision),
	}
	for _, o := range opts {
		o(p)
	}
	return p
}

var _ mailbox.Plugin = (*CrowdSecPlugin)(nil)
var _ mailbox.SendHook = (*CrowdSecPlugin)(nil)

func (p *CrowdSecPlugin) Name() string                  { return p.name }
func (p *CrowdSecPlugin) Init(_ context.Context) error  { return nil }
func (p *CrowdSecPlugin) Close(_ context.Context) error { return nil }
func (p *CrowdSecPlugin) AfterSend(_ context.Context, _ string, _ mbxstore.Message) error {
	return nil
}

// BeforeSend checks the X-SMTP-Remote-Addr header against the CrowdSec LAPI.
// Returns ErrRejected when the source IP has an active ban decision.
func (p *CrowdSecPlugin) BeforeSend(_ context.Context, _ string, draft mbxstore.DraftMessage) error {
	remoteAddr := draft.GetHeaders()["X-SMTP-Remote-Addr"]
	if remoteAddr == "" {
		return nil // not an SMTP message — skip
	}
	ipStr, _, err := net.SplitHostPort(remoteAddr)
	if err != nil {
		ipStr = remoteAddr // already a bare IP
	}

	banned, err := p.isBanned(ipStr)
	if err != nil {
		if !p.cfg.FailOpen {
			return reject(p.name, fmt.Sprintf("CrowdSec check failed: %v", err))
		}
		p.logger.Warn("crowdsec: LAPI unavailable — failing open", "plugin", p.name, "ip", ipStr, "error", err)
		return nil
	}
	if banned {
		return reject(p.name, fmt.Sprintf("IP %s has an active CrowdSec ban decision", ipStr))
	}
	return nil
}

// isBanned checks the local cache first, then queries the LAPI.
func (p *CrowdSecPlugin) isBanned(ip string) (bool, error) {
	// Fast path: cache hit.
	p.mu.Lock()
	if cached, ok := p.cache[ip]; ok && time.Now().Before(cached.expires) {
		banned := cached.banned
		p.mu.Unlock()
		return banned, nil
	}
	p.mu.Unlock()

	banned, err := p.queryLAPI(ip)
	if err != nil {
		return false, err
	}

	p.mu.Lock()
	p.cache[ip] = crowdSecDecision{banned: banned, expires: time.Now().Add(p.cfg.CacheTTL)}
	p.mu.Unlock()
	return banned, nil
}

// crowdSecDecisionEntry is the JSON shape returned by GET /v1/decisions.
type crowdSecDecisionEntry struct {
	Type  string `json:"type"`
	Scope string `json:"scope"`
	Value string `json:"value"`
}

func (p *CrowdSecPlugin) queryLAPI(ip string) (bool, error) {
	url := fmt.Sprintf("%s/v1/decisions?ip=%s&type=ban", p.cfg.Endpoint, ip)
	req, err := http.NewRequest(http.MethodGet, url, nil)
	if err != nil {
		return false, fmt.Errorf("build request: %w", err)
	}
	req.Header.Set("Authorization", "ApiKey "+p.cfg.APIKey)
	req.Header.Set("Accept", "application/json")

	resp, err := p.client.Do(req)
	if err != nil {
		return false, fmt.Errorf("LAPI request: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode == http.StatusNotFound {
		// 404 means no decisions for this IP — it's clean.
		return false, nil
	}
	if resp.StatusCode != http.StatusOK {
		return false, fmt.Errorf("LAPI returned HTTP %d", resp.StatusCode)
	}

	body, err := io.ReadAll(io.LimitReader(resp.Body, 64<<10)) // 64 KiB cap
	if err != nil {
		return false, fmt.Errorf("read LAPI response: %w", err)
	}

	// LAPI returns null (no decisions) or a JSON array of decisions.
	if string(body) == "null" {
		return false, nil
	}
	var decisions []crowdSecDecisionEntry
	if err := json.Unmarshal(body, &decisions); err != nil {
		return false, fmt.Errorf("parse LAPI response: %w", err)
	}
	for _, d := range decisions {
		if d.Type == "ban" {
			p.logger.Info("crowdsec: ban decision active", "plugin", p.name, "ip", ip)
			return true, nil
		}
	}
	return false, nil
}
