// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: postbox/v1/postbox.proto

package postboxpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DiscoverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverRequest) Reset() {
	*x = DiscoverRequest{}
	mi := &file_postbox_v1_postbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverRequest) ProtoMessage() {}

func (x *DiscoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_postbox_v1_postbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverRequest.ProtoReflect.Descriptor instead.
func (*DiscoverRequest) Descriptor() ([]byte, []int) {
	return file_postbox_v1_postbox_proto_rawDescGZIP(), []int{0}
}

func (x *DiscoverRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Mode          string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_postbox_v1_postbox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_postbox_v1_postbox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_postbox_v1_postbox_proto_rawDescGZIP(), []int{1}
}

func (x *NodeInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *NodeInfo) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type RegisterDomainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsDefault     bool                   `protobuf:"varint,2,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDomainRequest) Reset() {
	*x = RegisterDomainRequest{}
	mi := &file_postbox_v1_postbox_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDomainRequest) ProtoMessage() {}

func (x *RegisterDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_postbox_v1_postbox_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDomainRequest.ProtoReflect.Descriptor instead.
func (*RegisterDomainRequest) Descriptor() ([]byte, []int) {
	return file_postbox_v1_postbox_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterDomainRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterDomainRequest) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

type RemapDomainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	TargetNodeId  string                 `protobuf:"bytes,2,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemapDomainRequest) Reset() {
	*x = RemapDomainRequest{}
	mi := &file_postbox_v1_postbox_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemapDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemapDomainRequest) ProtoMessage() {}

func (x *RemapDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_postbox_v1_postbox_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemapDomainRequest.ProtoReflect.Descriptor instead.
func (*RemapDomainRequest) Descriptor() ([]byte, []int) {
	return file_postbox_v1_postbox_proto_rawDescGZIP(), []int{3}
}

func (x *RemapDomainRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *RemapDomainRequest) GetTargetNodeId() string {
	if x != nil {
		return x.TargetNodeId
	}
	return ""
}

type DomainInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	IsDefault     bool                   `protobuf:"varint,3,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainInfo) Reset() {
	*x = DomainInfo{}
	mi := &file_postbox_v1_postbox_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainInfo) ProtoMessage() {}

func (x *DomainInfo) ProtoReflect() protoreflect.Message {
	mi := &file_postbox_v1_postbox_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainInfo.ProtoReflect.Descriptor instead.
func (*DomainInfo) Descriptor() ([]byte, []int) {
	return file_postbox_v1_postbox_proto_rawDescGZIP(), []int{4}
}

func (x *DomainInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DomainInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *DomainInfo) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

type ListDomainsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domains       []*DomainInfo          `protobuf:"bytes,1,rep,name=domains,proto3" json:"domains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDomainsResponse) Reset() {
	*x = ListDomainsResponse{}
	mi := &file_postbox_v1_postbox_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDomainsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDomainsResponse) ProtoMessage() {}

func (x *ListDomainsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_postbox_v1_postbox_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDomainsResponse.ProtoReflect.Descriptor instead.
func (*ListDomainsResponse) Descriptor() ([]byte, []int) {
	return file_postbox_v1_postbox_proto_rawDescGZIP(), []int{5}
}

func (x *ListDomainsResponse) GetDomains() []*DomainInfo {
	if x != nil {
		return x.Domains
	}
	return nil
}

type RegisterUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Email string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// public_key is the user's Ed25519 public key (base64-encoded).
	// Required for AI agents; empty for human users.
	PublicKey string            `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Metadata  map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// type classifies the principal: "human", "agent", "service", or "" (unset).
	Type          string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserRequest) Reset() {
	*x = RegisterUserRequest{}
	mi := &file_postbox_v1_postbox_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserRequest) ProtoMessage() {}

func (x *RegisterUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_postbox_v1_postbox_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserRequest.ProtoReflect.Descriptor instead.
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return file_postbox_v1_postbox_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterUserRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *RegisterUserRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RegisterUserRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_postbox_v1_postbox_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_postbox_v1_postbox_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_postbox_v1_postbox_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// UserProfile is the full registration record for any mailbox principal.
type UserProfile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Email string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// public_key is the user's Ed25519 public key (base64-encoded); empty for humans.
	PublicKey string            `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Metadata  map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	NodeId    string            `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// type classifies the principal: "human", "agent", "service", or "" (unset).
	Type          string `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_postbox_v1_postbox_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_postbox_v1_postbox_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_postbox_v1_postbox_proto_rawDescGZIP(), []int{8}
}

func (x *UserProfile) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserProfile) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *UserProfile) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UserProfile) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *UserProfile) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type SearchUsersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// metadata_filters is a set of key-value pairs. Returned users must satisfy
	// all filters. Values are substring-matched (e.g. skills="web-search" matches
	// metadata["skills"]="web-search,image-gen").
	MetadataFilters map[string]string `protobuf:"bytes,1,rep,name=metadata_filters,json=metadataFilters,proto3" json:"metadata_filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SearchUsersRequest) Reset() {
	*x = SearchUsersRequest{}
	mi := &file_postbox_v1_postbox_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersRequest) ProtoMessage() {}

func (x *SearchUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_postbox_v1_postbox_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersRequest.ProtoReflect.Descriptor instead.
func (*SearchUsersRequest) Descriptor() ([]byte, []int) {
	return file_postbox_v1_postbox_proto_rawDescGZIP(), []int{9}
}

func (x *SearchUsersRequest) GetMetadataFilters() map[string]string {
	if x != nil {
		return x.MetadataFilters
	}
	return nil
}

type SearchUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserProfile         `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsersResponse) Reset() {
	*x = SearchUsersResponse{}
	mi := &file_postbox_v1_postbox_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersResponse) ProtoMessage() {}

func (x *SearchUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_postbox_v1_postbox_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersResponse.ProtoReflect.Descriptor instead.
func (*SearchUsersResponse) Descriptor() ([]byte, []int) {
	return file_postbox_v1_postbox_proto_rawDescGZIP(), []int{10}
}

func (x *SearchUsersResponse) GetUsers() []*UserProfile {
	if x != nil {
		return x.Users
	}
	return nil
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserProfile         `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_postbox_v1_postbox_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_postbox_v1_postbox_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_postbox_v1_postbox_proto_rawDescGZIP(), []int{11}
}

func (x *ListUsersResponse) GetUsers() []*UserProfile {
	if x != nil {
		return x.Users
	}
	return nil
}

type NodePublicKeyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// public_key is the node's Ed25519 public key, base64-encoded (standard encoding).
	PublicKey string `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	NodeId    string `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// key_id is an opaque rotation token. Agents should re-fetch the key when
	// they encounter a key_id they have not seen before.
	KeyId         string `protobuf:"bytes,3,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodePublicKeyResponse) Reset() {
	*x = NodePublicKeyResponse{}
	mi := &file_postbox_v1_postbox_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodePublicKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodePublicKeyResponse) ProtoMessage() {}

func (x *NodePublicKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_postbox_v1_postbox_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodePublicKeyResponse.ProtoReflect.Descriptor instead.
func (*NodePublicKeyResponse) Descriptor() ([]byte, []int) {
	return file_postbox_v1_postbox_proto_rawDescGZIP(), []int{12}
}

func (x *NodePublicKeyResponse) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *NodePublicKeyResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodePublicKeyResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_postbox_v1_postbox_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_postbox_v1_postbox_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_postbox_v1_postbox_proto_rawDescGZIP(), []int{13}
}

func (x *Response) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StatusReport struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NodeId           string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Mode             string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	DomainCount      int64                  `protobuf:"varint,3,opt,name=domain_count,json=domainCount,proto3" json:"domain_count,omitempty"`
	UserCount        int64                  `protobuf:"varint,4,opt,name=user_count,json=userCount,proto3" json:"user_count,omitempty"`
	MailboxConnected bool                   `protobuf:"varint,5,opt,name=mailbox_connected,json=mailboxConnected,proto3" json:"mailbox_connected,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StatusReport) Reset() {
	*x = StatusReport{}
	mi := &file_postbox_v1_postbox_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusReport) ProtoMessage() {}

func (x *StatusReport) ProtoReflect() protoreflect.Message {
	mi := &file_postbox_v1_postbox_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusReport.ProtoReflect.Descriptor instead.
func (*StatusReport) Descriptor() ([]byte, []int) {
	return file_postbox_v1_postbox_proto_rawDescGZIP(), []int{14}
}

func (x *StatusReport) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *StatusReport) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *StatusReport) GetDomainCount() int64 {
	if x != nil {
		return x.DomainCount
	}
	return 0
}

func (x *StatusReport) GetUserCount() int64 {
	if x != nil {
		return x.UserCount
	}
	return 0
}

func (x *StatusReport) GetMailboxConnected() bool {
	if x != nil {
		return x.MailboxConnected
	}
	return false
}

type SMTPConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Port              int32                  `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	Domain            string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	AllowInsecureAuth bool                   `protobuf:"varint,3,opt,name=allow_insecure_auth,json=allowInsecureAuth,proto3" json:"allow_insecure_auth,omitempty"`
	MaxMessageBytes   int64                  `protobuf:"varint,4,opt,name=max_message_bytes,json=maxMessageBytes,proto3" json:"max_message_bytes,omitempty"`
	MaxRecipients     int32                  `protobuf:"varint,5,opt,name=max_recipients,json=maxRecipients,proto3" json:"max_recipients,omitempty"`
	ReadTimeoutSecs   int32                  `protobuf:"varint,6,opt,name=read_timeout_secs,json=readTimeoutSecs,proto3" json:"read_timeout_secs,omitempty"`
	WriteTimeoutSecs  int32                  `protobuf:"varint,7,opt,name=write_timeout_secs,json=writeTimeoutSecs,proto3" json:"write_timeout_secs,omitempty"`
	MaxConnsPerSec    float64                `protobuf:"fixed64,8,opt,name=max_conns_per_sec,json=maxConnsPerSec,proto3" json:"max_conns_per_sec,omitempty"`
	BurstConns        int32                  `protobuf:"varint,9,opt,name=burst_conns,json=burstConns,proto3" json:"burst_conns,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SMTPConfig) Reset() {
	*x = SMTPConfig{}
	mi := &file_postbox_v1_postbox_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SMTPConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMTPConfig) ProtoMessage() {}

func (x *SMTPConfig) ProtoReflect() protoreflect.Message {
	mi := &file_postbox_v1_postbox_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMTPConfig.ProtoReflect.Descriptor instead.
func (*SMTPConfig) Descriptor() ([]byte, []int) {
	return file_postbox_v1_postbox_proto_rawDescGZIP(), []int{15}
}

func (x *SMTPConfig) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *SMTPConfig) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *SMTPConfig) GetAllowInsecureAuth() bool {
	if x != nil {
		return x.AllowInsecureAuth
	}
	return false
}

func (x *SMTPConfig) GetMaxMessageBytes() int64 {
	if x != nil {
		return x.MaxMessageBytes
	}
	return 0
}

func (x *SMTPConfig) GetMaxRecipients() int32 {
	if x != nil {
		return x.MaxRecipients
	}
	return 0
}

func (x *SMTPConfig) GetReadTimeoutSecs() int32 {
	if x != nil {
		return x.ReadTimeoutSecs
	}
	return 0
}

func (x *SMTPConfig) GetWriteTimeoutSecs() int32 {
	if x != nil {
		return x.WriteTimeoutSecs
	}
	return 0
}

func (x *SMTPConfig) GetMaxConnsPerSec() float64 {
	if x != nil {
		return x.MaxConnsPerSec
	}
	return 0
}

func (x *SMTPConfig) GetBurstConns() int32 {
	if x != nil {
		return x.BurstConns
	}
	return 0
}

type SMTPStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Running       bool                   `protobuf:"varint,1,opt,name=running,proto3" json:"running,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Domain        string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SMTPStatus) Reset() {
	*x = SMTPStatus{}
	mi := &file_postbox_v1_postbox_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SMTPStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMTPStatus) ProtoMessage() {}

func (x *SMTPStatus) ProtoReflect() protoreflect.Message {
	mi := &file_postbox_v1_postbox_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMTPStatus.ProtoReflect.Descriptor instead.
func (*SMTPStatus) Descriptor() ([]byte, []int) {
	return file_postbox_v1_postbox_proto_rawDescGZIP(), []int{16}
}

func (x *SMTPStatus) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *SMTPStatus) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *SMTPStatus) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type GetDeliveryStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	RecipientId   string                 `protobuf:"bytes,2,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeliveryStatusRequest) Reset() {
	*x = GetDeliveryStatusRequest{}
	mi := &file_postbox_v1_postbox_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeliveryStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeliveryStatusRequest) ProtoMessage() {}

func (x *GetDeliveryStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_postbox_v1_postbox_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeliveryStatusRequest.ProtoReflect.Descriptor instead.
func (*GetDeliveryStatusRequest) Descriptor() ([]byte, []int) {
	return file_postbox_v1_postbox_proto_rawDescGZIP(), []int{17}
}

func (x *GetDeliveryStatusRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *GetDeliveryStatusRequest) GetRecipientId() string {
	if x != nil {
		return x.RecipientId
	}
	return ""
}

type DeliveryStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	RecipientId   string                 `protobuf:"bytes,2,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"`
	EndpointUrl   string                 `protobuf:"bytes,3,opt,name=endpoint_url,json=endpointUrl,proto3" json:"endpoint_url,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // "pending" | "delivered" | "failed" | "dead"
	Attempts      int32                  `protobuf:"varint,5,opt,name=attempts,proto3" json:"attempts,omitempty"`
	MaxAttempts   int32                  `protobuf:"varint,6,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	LastError     string                 `protobuf:"bytes,7,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	NextRetryAt   string                 `protobuf:"bytes,8,opt,name=next_retry_at,json=nextRetryAt,proto3" json:"next_retry_at,omitempty"` // RFC3339; empty when no retry is scheduled
	DeliveredAt   string                 `protobuf:"bytes,9,opt,name=delivered_at,json=deliveredAt,proto3" json:"delivered_at,omitempty"`   // RFC3339; empty when not yet delivered
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryStatusResponse) Reset() {
	*x = DeliveryStatusResponse{}
	mi := &file_postbox_v1_postbox_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryStatusResponse) ProtoMessage() {}

func (x *DeliveryStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_postbox_v1_postbox_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryStatusResponse.ProtoReflect.Descriptor instead.
func (*DeliveryStatusResponse) Descriptor() ([]byte, []int) {
	return file_postbox_v1_postbox_proto_rawDescGZIP(), []int{18}
}

func (x *DeliveryStatusResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *DeliveryStatusResponse) GetRecipientId() string {
	if x != nil {
		return x.RecipientId
	}
	return ""
}

func (x *DeliveryStatusResponse) GetEndpointUrl() string {
	if x != nil {
		return x.EndpointUrl
	}
	return ""
}

func (x *DeliveryStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeliveryStatusResponse) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *DeliveryStatusResponse) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *DeliveryStatusResponse) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *DeliveryStatusResponse) GetNextRetryAt() string {
	if x != nil {
		return x.NextRetryAt
	}
	return ""
}

func (x *DeliveryStatusResponse) GetDeliveredAt() string {
	if x != nil {
		return x.DeliveredAt
	}
	return ""
}

type ListDeliveryFailuresRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter by user email; empty returns failures for all users.
	RecipientId   string `protobuf:"bytes,1,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeliveryFailuresRequest) Reset() {
	*x = ListDeliveryFailuresRequest{}
	mi := &file_postbox_v1_postbox_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeliveryFailuresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeliveryFailuresRequest) ProtoMessage() {}

func (x *ListDeliveryFailuresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_postbox_v1_postbox_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeliveryFailuresRequest.ProtoReflect.Descriptor instead.
func (*ListDeliveryFailuresRequest) Descriptor() ([]byte, []int) {
	return file_postbox_v1_postbox_proto_rawDescGZIP(), []int{19}
}

func (x *ListDeliveryFailuresRequest) GetRecipientId() string {
	if x != nil {
		return x.RecipientId
	}
	return ""
}

type ListDeliveryFailuresResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Jobs          []*DeliveryStatusResponse `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeliveryFailuresResponse) Reset() {
	*x = ListDeliveryFailuresResponse{}
	mi := &file_postbox_v1_postbox_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeliveryFailuresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeliveryFailuresResponse) ProtoMessage() {}

func (x *ListDeliveryFailuresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_postbox_v1_postbox_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeliveryFailuresResponse.ProtoReflect.Descriptor instead.
func (*ListDeliveryFailuresResponse) Descriptor() ([]byte, []int) {
	return file_postbox_v1_postbox_proto_rawDescGZIP(), []int{20}
}

func (x *ListDeliveryFailuresResponse) GetJobs() []*DeliveryStatusResponse {
	if x != nil {
		return x.Jobs
	}
	return nil
}

var File_postbox_v1_postbox_proto protoreflect.FileDescriptor

const file_postbox_v1_postbox_proto_rawDesc = "" +
	"\n" +
	"\x18postbox/v1/postbox.proto\x12\n" +
	"postbox.v1\x1a\x1bgoogle/protobuf/empty.proto\")\n" +
	"\x0fDiscoverRequest\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\"Q\n" +
	"\bNodeInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\"J\n" +
	"\x15RegisterDomainRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"is_default\x18\x02 \x01(\bR\tisDefault\"R\n" +
	"\x12RemapDomainRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12$\n" +
	"\x0etarget_node_id\x18\x02 \x01(\tR\ftargetNodeId\"X\n" +
	"\n" +
	"DomainInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"is_default\x18\x03 \x01(\bR\tisDefault\"G\n" +
	"\x13ListDomainsResponse\x120\n" +
	"\adomains\x18\x01 \x03(\v2\x16.postbox.v1.DomainInfoR\adomains\"\xe6\x01\n" +
	"\x13RegisterUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12I\n" +
	"\bmetadata\x18\x03 \x03(\v2-.postbox.v1.RegisterUserRequest.MetadataEntryR\bmetadata\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"&\n" +
	"\x0eGetUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"\xef\x01\n" +
	"\vUserProfile\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12A\n" +
	"\bmetadata\x18\x03 \x03(\v2%.postbox.v1.UserProfile.MetadataEntryR\bmetadata\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb8\x01\n" +
	"\x12SearchUsersRequest\x12^\n" +
	"\x10metadata_filters\x18\x01 \x03(\v23.postbox.v1.SearchUsersRequest.MetadataFiltersEntryR\x0fmetadataFilters\x1aB\n" +
	"\x14MetadataFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"D\n" +
	"\x13SearchUsersResponse\x12-\n" +
	"\x05users\x18\x01 \x03(\v2\x17.postbox.v1.UserProfileR\x05users\"B\n" +
	"\x11ListUsersResponse\x12-\n" +
	"\x05users\x18\x01 \x03(\v2\x17.postbox.v1.UserProfileR\x05users\"f\n" +
	"\x15NodePublicKeyResponse\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x15\n" +
	"\x06key_id\x18\x03 \x01(\tR\x05keyId\"4\n" +
	"\bResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xaa\x01\n" +
	"\fStatusReport\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12!\n" +
	"\fdomain_count\x18\x03 \x01(\x03R\vdomainCount\x12\x1d\n" +
	"\n" +
	"user_count\x18\x04 \x01(\x03R\tuserCount\x12+\n" +
	"\x11mailbox_connected\x18\x05 \x01(\bR\x10mailboxConnected\"\xe1\x02\n" +
	"\n" +
	"SMTPConfig\x12\x12\n" +
	"\x04port\x18\x01 \x01(\x05R\x04port\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12.\n" +
	"\x13allow_insecure_auth\x18\x03 \x01(\bR\x11allowInsecureAuth\x12*\n" +
	"\x11max_message_bytes\x18\x04 \x01(\x03R\x0fmaxMessageBytes\x12%\n" +
	"\x0emax_recipients\x18\x05 \x01(\x05R\rmaxRecipients\x12*\n" +
	"\x11read_timeout_secs\x18\x06 \x01(\x05R\x0freadTimeoutSecs\x12,\n" +
	"\x12write_timeout_secs\x18\a \x01(\x05R\x10writeTimeoutSecs\x12)\n" +
	"\x11max_conns_per_sec\x18\b \x01(\x01R\x0emaxConnsPerSec\x12\x1f\n" +
	"\vburst_conns\x18\t \x01(\x05R\n" +
	"burstConns\"R\n" +
	"\n" +
	"SMTPStatus\x12\x18\n" +
	"\arunning\x18\x01 \x01(\bR\arunning\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\"\\\n" +
	"\x18GetDeliveryStatusRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12!\n" +
	"\frecipient_id\x18\x02 \x01(\tR\vrecipientId\"\xba\x02\n" +
	"\x16DeliveryStatusResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12!\n" +
	"\frecipient_id\x18\x02 \x01(\tR\vrecipientId\x12!\n" +
	"\fendpoint_url\x18\x03 \x01(\tR\vendpointUrl\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1a\n" +
	"\battempts\x18\x05 \x01(\x05R\battempts\x12!\n" +
	"\fmax_attempts\x18\x06 \x01(\x05R\vmaxAttempts\x12\x1d\n" +
	"\n" +
	"last_error\x18\a \x01(\tR\tlastError\x12\"\n" +
	"\rnext_retry_at\x18\b \x01(\tR\vnextRetryAt\x12!\n" +
	"\fdelivered_at\x18\t \x01(\tR\vdeliveredAt\"@\n" +
	"\x1bListDeliveryFailuresRequest\x12!\n" +
	"\frecipient_id\x18\x01 \x01(\tR\vrecipientId\"V\n" +
	"\x1cListDeliveryFailuresResponse\x126\n" +
	"\x04jobs\x18\x01 \x03(\v2\".postbox.v1.DeliveryStatusResponseR\x04jobs2\xd0\b\n" +
	"\x0ePostboxService\x12=\n" +
	"\bDiscover\x12\x1b.postbox.v1.DiscoverRequest\x1a\x14.postbox.v1.NodeInfo\x12I\n" +
	"\x0eRegisterDomain\x12!.postbox.v1.RegisterDomainRequest\x1a\x14.postbox.v1.Response\x12E\n" +
	"\fRegisterUser\x12\x1f.postbox.v1.RegisterUserRequest\x1a\x14.postbox.v1.Response\x12>\n" +
	"\aGetUser\x12\x1a.postbox.v1.GetUserRequest\x1a\x17.postbox.v1.UserProfile\x12N\n" +
	"\vSearchUsers\x12\x1e.postbox.v1.SearchUsersRequest\x1a\x1f.postbox.v1.SearchUsersResponse\x12B\n" +
	"\tListUsers\x12\x16.google.protobuf.Empty\x1a\x1d.postbox.v1.ListUsersResponse\x12M\n" +
	"\x10GetNodePublicKey\x12\x16.google.protobuf.Empty\x1a!.postbox.v1.NodePublicKeyResponse\x12=\n" +
	"\tGetStatus\x12\x16.google.protobuf.Empty\x1a\x18.postbox.v1.StatusReport\x12C\n" +
	"\vRemapDomain\x12\x1e.postbox.v1.RemapDomainRequest\x1a\x14.postbox.v1.Response\x12F\n" +
	"\vListDomains\x12\x16.google.protobuf.Empty\x1a\x1f.postbox.v1.ListDomainsResponse\x129\n" +
	"\tStartSMTP\x12\x16.postbox.v1.SMTPConfig\x1a\x14.postbox.v1.Response\x128\n" +
	"\bStopSMTP\x12\x16.google.protobuf.Empty\x1a\x14.postbox.v1.Response\x12?\n" +
	"\rGetSMTPStatus\x12\x16.google.protobuf.Empty\x1a\x16.postbox.v1.SMTPStatus\x12]\n" +
	"\x11GetDeliveryStatus\x12$.postbox.v1.GetDeliveryStatusRequest\x1a\".postbox.v1.DeliveryStatusResponse\x12i\n" +
	"\x14ListDeliveryFailures\x12'.postbox.v1.ListDeliveryFailuresRequest\x1a(.postbox.v1.ListDeliveryFailuresResponseB8Z6github.com/rbaliyan/postbox/proto/postbox/v1;postboxpbb\x06proto3"

var (
	file_postbox_v1_postbox_proto_rawDescOnce sync.Once
	file_postbox_v1_postbox_proto_rawDescData []byte
)

func file_postbox_v1_postbox_proto_rawDescGZIP() []byte {
	file_postbox_v1_postbox_proto_rawDescOnce.Do(func() {
		file_postbox_v1_postbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_postbox_v1_postbox_proto_rawDesc), len(file_postbox_v1_postbox_proto_rawDesc)))
	})
	return file_postbox_v1_postbox_proto_rawDescData
}

var file_postbox_v1_postbox_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_postbox_v1_postbox_proto_goTypes = []any{
	(*DiscoverRequest)(nil),              // 0: postbox.v1.DiscoverRequest
	(*NodeInfo)(nil),                     // 1: postbox.v1.NodeInfo
	(*RegisterDomainRequest)(nil),        // 2: postbox.v1.RegisterDomainRequest
	(*RemapDomainRequest)(nil),           // 3: postbox.v1.RemapDomainRequest
	(*DomainInfo)(nil),                   // 4: postbox.v1.DomainInfo
	(*ListDomainsResponse)(nil),          // 5: postbox.v1.ListDomainsResponse
	(*RegisterUserRequest)(nil),          // 6: postbox.v1.RegisterUserRequest
	(*GetUserRequest)(nil),               // 7: postbox.v1.GetUserRequest
	(*UserProfile)(nil),                  // 8: postbox.v1.UserProfile
	(*SearchUsersRequest)(nil),           // 9: postbox.v1.SearchUsersRequest
	(*SearchUsersResponse)(nil),          // 10: postbox.v1.SearchUsersResponse
	(*ListUsersResponse)(nil),            // 11: postbox.v1.ListUsersResponse
	(*NodePublicKeyResponse)(nil),        // 12: postbox.v1.NodePublicKeyResponse
	(*Response)(nil),                     // 13: postbox.v1.Response
	(*StatusReport)(nil),                 // 14: postbox.v1.StatusReport
	(*SMTPConfig)(nil),                   // 15: postbox.v1.SMTPConfig
	(*SMTPStatus)(nil),                   // 16: postbox.v1.SMTPStatus
	(*GetDeliveryStatusRequest)(nil),     // 17: postbox.v1.GetDeliveryStatusRequest
	(*DeliveryStatusResponse)(nil),       // 18: postbox.v1.DeliveryStatusResponse
	(*ListDeliveryFailuresRequest)(nil),  // 19: postbox.v1.ListDeliveryFailuresRequest
	(*ListDeliveryFailuresResponse)(nil), // 20: postbox.v1.ListDeliveryFailuresResponse
	nil,                                  // 21: postbox.v1.RegisterUserRequest.MetadataEntry
	nil,                                  // 22: postbox.v1.UserProfile.MetadataEntry
	nil,                                  // 23: postbox.v1.SearchUsersRequest.MetadataFiltersEntry
	(*emptypb.Empty)(nil),                // 24: google.protobuf.Empty
}
var file_postbox_v1_postbox_proto_depIdxs = []int32{
	4,  // 0: postbox.v1.ListDomainsResponse.domains:type_name -> postbox.v1.DomainInfo
	21, // 1: postbox.v1.RegisterUserRequest.metadata:type_name -> postbox.v1.RegisterUserRequest.MetadataEntry
	22, // 2: postbox.v1.UserProfile.metadata:type_name -> postbox.v1.UserProfile.MetadataEntry
	23, // 3: postbox.v1.SearchUsersRequest.metadata_filters:type_name -> postbox.v1.SearchUsersRequest.MetadataFiltersEntry
	8,  // 4: postbox.v1.SearchUsersResponse.users:type_name -> postbox.v1.UserProfile
	8,  // 5: postbox.v1.ListUsersResponse.users:type_name -> postbox.v1.UserProfile
	18, // 6: postbox.v1.ListDeliveryFailuresResponse.jobs:type_name -> postbox.v1.DeliveryStatusResponse
	0,  // 7: postbox.v1.PostboxService.Discover:input_type -> postbox.v1.DiscoverRequest
	2,  // 8: postbox.v1.PostboxService.RegisterDomain:input_type -> postbox.v1.RegisterDomainRequest
	6,  // 9: postbox.v1.PostboxService.RegisterUser:input_type -> postbox.v1.RegisterUserRequest
	7,  // 10: postbox.v1.PostboxService.GetUser:input_type -> postbox.v1.GetUserRequest
	9,  // 11: postbox.v1.PostboxService.SearchUsers:input_type -> postbox.v1.SearchUsersRequest
	24, // 12: postbox.v1.PostboxService.ListUsers:input_type -> google.protobuf.Empty
	24, // 13: postbox.v1.PostboxService.GetNodePublicKey:input_type -> google.protobuf.Empty
	24, // 14: postbox.v1.PostboxService.GetStatus:input_type -> google.protobuf.Empty
	3,  // 15: postbox.v1.PostboxService.RemapDomain:input_type -> postbox.v1.RemapDomainRequest
	24, // 16: postbox.v1.PostboxService.ListDomains:input_type -> google.protobuf.Empty
	15, // 17: postbox.v1.PostboxService.StartSMTP:input_type -> postbox.v1.SMTPConfig
	24, // 18: postbox.v1.PostboxService.StopSMTP:input_type -> google.protobuf.Empty
	24, // 19: postbox.v1.PostboxService.GetSMTPStatus:input_type -> google.protobuf.Empty
	17, // 20: postbox.v1.PostboxService.GetDeliveryStatus:input_type -> postbox.v1.GetDeliveryStatusRequest
	19, // 21: postbox.v1.PostboxService.ListDeliveryFailures:input_type -> postbox.v1.ListDeliveryFailuresRequest
	1,  // 22: postbox.v1.PostboxService.Discover:output_type -> postbox.v1.NodeInfo
	13, // 23: postbox.v1.PostboxService.RegisterDomain:output_type -> postbox.v1.Response
	13, // 24: postbox.v1.PostboxService.RegisterUser:output_type -> postbox.v1.Response
	8,  // 25: postbox.v1.PostboxService.GetUser:output_type -> postbox.v1.UserProfile
	10, // 26: postbox.v1.PostboxService.SearchUsers:output_type -> postbox.v1.SearchUsersResponse
	11, // 27: postbox.v1.PostboxService.ListUsers:output_type -> postbox.v1.ListUsersResponse
	12, // 28: postbox.v1.PostboxService.GetNodePublicKey:output_type -> postbox.v1.NodePublicKeyResponse
	14, // 29: postbox.v1.PostboxService.GetStatus:output_type -> postbox.v1.StatusReport
	13, // 30: postbox.v1.PostboxService.RemapDomain:output_type -> postbox.v1.Response
	5,  // 31: postbox.v1.PostboxService.ListDomains:output_type -> postbox.v1.ListDomainsResponse
	13, // 32: postbox.v1.PostboxService.StartSMTP:output_type -> postbox.v1.Response
	13, // 33: postbox.v1.PostboxService.StopSMTP:output_type -> postbox.v1.Response
	16, // 34: postbox.v1.PostboxService.GetSMTPStatus:output_type -> postbox.v1.SMTPStatus
	18, // 35: postbox.v1.PostboxService.GetDeliveryStatus:output_type -> postbox.v1.DeliveryStatusResponse
	20, // 36: postbox.v1.PostboxService.ListDeliveryFailures:output_type -> postbox.v1.ListDeliveryFailuresResponse
	22, // [22:37] is the sub-list for method output_type
	7,  // [7:22] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_postbox_v1_postbox_proto_init() }
func file_postbox_v1_postbox_proto_init() {
	if File_postbox_v1_postbox_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_postbox_v1_postbox_proto_rawDesc), len(file_postbox_v1_postbox_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_postbox_v1_postbox_proto_goTypes,
		DependencyIndexes: file_postbox_v1_postbox_proto_depIdxs,
		MessageInfos:      file_postbox_v1_postbox_proto_msgTypes,
	}.Build()
	File_postbox_v1_postbox_proto = out.File
	file_postbox_v1_postbox_proto_goTypes = nil
	file_postbox_v1_postbox_proto_depIdxs = nil
}
