// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: postbox/v1/postbox.proto

package postboxpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PostboxService_Discover_FullMethodName             = "/postbox.v1.PostboxService/Discover"
	PostboxService_RegisterDomain_FullMethodName       = "/postbox.v1.PostboxService/RegisterDomain"
	PostboxService_RegisterUser_FullMethodName         = "/postbox.v1.PostboxService/RegisterUser"
	PostboxService_GetUser_FullMethodName              = "/postbox.v1.PostboxService/GetUser"
	PostboxService_SearchUsers_FullMethodName          = "/postbox.v1.PostboxService/SearchUsers"
	PostboxService_ListUsers_FullMethodName            = "/postbox.v1.PostboxService/ListUsers"
	PostboxService_GetNodePublicKey_FullMethodName     = "/postbox.v1.PostboxService/GetNodePublicKey"
	PostboxService_GetStatus_FullMethodName            = "/postbox.v1.PostboxService/GetStatus"
	PostboxService_RemapDomain_FullMethodName          = "/postbox.v1.PostboxService/RemapDomain"
	PostboxService_ListDomains_FullMethodName          = "/postbox.v1.PostboxService/ListDomains"
	PostboxService_StartSMTP_FullMethodName            = "/postbox.v1.PostboxService/StartSMTP"
	PostboxService_StopSMTP_FullMethodName             = "/postbox.v1.PostboxService/StopSMTP"
	PostboxService_GetSMTPStatus_FullMethodName        = "/postbox.v1.PostboxService/GetSMTPStatus"
	PostboxService_GetDeliveryStatus_FullMethodName    = "/postbox.v1.PostboxService/GetDeliveryStatus"
	PostboxService_ListDeliveryFailures_FullMethodName = "/postbox.v1.PostboxService/ListDeliveryFailures"
)

// PostboxServiceClient is the client API for PostboxService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PostboxService is the agent communication backbone for AI agent swarms.
type PostboxServiceClient interface {
	// Discover returns the node responsible for a target domain or user email.
	Discover(ctx context.Context, in *DiscoverRequest, opts ...grpc.CallOption) (*NodeInfo, error)
	// RegisterDomain claims a domain for the local node.
	// Returns ALREADY_EXISTS if the domain is already claimed by a different node.
	RegisterDomain(ctx context.Context, in *RegisterDomainRequest, opts ...grpc.CallOption) (*Response, error)
	// RegisterUser registers a mailbox principal — human, AI agent, or service.
	// Set type="agent" for AI agents; use metadata for skills, endpoint, region, etc.
	// Idempotent: returns ok=true if the user already exists.
	RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*Response, error)
	// GetUser retrieves a user profile by email address.
	// Returns NOT_FOUND if the user is not registered.
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*UserProfile, error)
	// SearchUsers returns users whose metadata matches all supplied filters.
	// Filter values are substring-matched, so filtering skills="web-search"
	// matches metadata["skills"]="web-search,image-gen".
	SearchUsers(ctx context.Context, in *SearchUsersRequest, opts ...grpc.CallOption) (*SearchUsersResponse, error)
	// ListUsers returns all registered users.
	ListUsers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListUsersResponse, error)
	// GetNodePublicKey returns the node's Ed25519 public key.
	// Agents call this once during onboarding and cache the result.
	// Use the returned key to verify X-Postbox-Signature-Ed25519 headers on
	// incoming webhook POSTs.
	GetNodePublicKey(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*NodePublicKeyResponse, error)
	// GetStatus returns health and capacity metrics for the local node.
	GetStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*StatusReport, error)
	// RemapDomain reassigns a domain to a different node (admin operation).
	RemapDomain(ctx context.Context, in *RemapDomainRequest, opts ...grpc.CallOption) (*Response, error)
	// ListDomains returns all registered domains.
	ListDomains(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListDomainsResponse, error)
	// StartSMTP starts the SMTP listener with the given config.
	// Returns FAILED_PRECONDITION if the listener is already running.
	StartSMTP(ctx context.Context, in *SMTPConfig, opts ...grpc.CallOption) (*Response, error)
	// StopSMTP stops the running SMTP listener.
	// Returns FAILED_PRECONDITION if the listener is not currently running.
	StopSMTP(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Response, error)
	// GetSMTPStatus returns the current SMTP listener state.
	GetSMTPStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SMTPStatus, error)
	// GetDeliveryStatus returns webhook delivery attempts for a message/recipient pair.
	// Returns NOT_FOUND if no delivery job exists.
	GetDeliveryStatus(ctx context.Context, in *GetDeliveryStatusRequest, opts ...grpc.CallOption) (*DeliveryStatusResponse, error)
	// ListDeliveryFailures returns failed and dead delivery jobs.
	// Filter by recipient_id to narrow results to a specific user.
	ListDeliveryFailures(ctx context.Context, in *ListDeliveryFailuresRequest, opts ...grpc.CallOption) (*ListDeliveryFailuresResponse, error)
}

type postboxServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPostboxServiceClient(cc grpc.ClientConnInterface) PostboxServiceClient {
	return &postboxServiceClient{cc}
}

func (c *postboxServiceClient) Discover(ctx context.Context, in *DiscoverRequest, opts ...grpc.CallOption) (*NodeInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeInfo)
	err := c.cc.Invoke(ctx, PostboxService_Discover_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postboxServiceClient) RegisterDomain(ctx context.Context, in *RegisterDomainRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, PostboxService_RegisterDomain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postboxServiceClient) RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, PostboxService_RegisterUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postboxServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*UserProfile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserProfile)
	err := c.cc.Invoke(ctx, PostboxService_GetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postboxServiceClient) SearchUsers(ctx context.Context, in *SearchUsersRequest, opts ...grpc.CallOption) (*SearchUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchUsersResponse)
	err := c.cc.Invoke(ctx, PostboxService_SearchUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postboxServiceClient) ListUsers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUsersResponse)
	err := c.cc.Invoke(ctx, PostboxService_ListUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postboxServiceClient) GetNodePublicKey(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*NodePublicKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodePublicKeyResponse)
	err := c.cc.Invoke(ctx, PostboxService_GetNodePublicKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postboxServiceClient) GetStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*StatusReport, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusReport)
	err := c.cc.Invoke(ctx, PostboxService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postboxServiceClient) RemapDomain(ctx context.Context, in *RemapDomainRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, PostboxService_RemapDomain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postboxServiceClient) ListDomains(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListDomainsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDomainsResponse)
	err := c.cc.Invoke(ctx, PostboxService_ListDomains_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postboxServiceClient) StartSMTP(ctx context.Context, in *SMTPConfig, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, PostboxService_StartSMTP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postboxServiceClient) StopSMTP(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, PostboxService_StopSMTP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postboxServiceClient) GetSMTPStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SMTPStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SMTPStatus)
	err := c.cc.Invoke(ctx, PostboxService_GetSMTPStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postboxServiceClient) GetDeliveryStatus(ctx context.Context, in *GetDeliveryStatusRequest, opts ...grpc.CallOption) (*DeliveryStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliveryStatusResponse)
	err := c.cc.Invoke(ctx, PostboxService_GetDeliveryStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postboxServiceClient) ListDeliveryFailures(ctx context.Context, in *ListDeliveryFailuresRequest, opts ...grpc.CallOption) (*ListDeliveryFailuresResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDeliveryFailuresResponse)
	err := c.cc.Invoke(ctx, PostboxService_ListDeliveryFailures_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostboxServiceServer is the server API for PostboxService service.
// All implementations must embed UnimplementedPostboxServiceServer
// for forward compatibility.
//
// PostboxService is the agent communication backbone for AI agent swarms.
type PostboxServiceServer interface {
	// Discover returns the node responsible for a target domain or user email.
	Discover(context.Context, *DiscoverRequest) (*NodeInfo, error)
	// RegisterDomain claims a domain for the local node.
	// Returns ALREADY_EXISTS if the domain is already claimed by a different node.
	RegisterDomain(context.Context, *RegisterDomainRequest) (*Response, error)
	// RegisterUser registers a mailbox principal — human, AI agent, or service.
	// Set type="agent" for AI agents; use metadata for skills, endpoint, region, etc.
	// Idempotent: returns ok=true if the user already exists.
	RegisterUser(context.Context, *RegisterUserRequest) (*Response, error)
	// GetUser retrieves a user profile by email address.
	// Returns NOT_FOUND if the user is not registered.
	GetUser(context.Context, *GetUserRequest) (*UserProfile, error)
	// SearchUsers returns users whose metadata matches all supplied filters.
	// Filter values are substring-matched, so filtering skills="web-search"
	// matches metadata["skills"]="web-search,image-gen".
	SearchUsers(context.Context, *SearchUsersRequest) (*SearchUsersResponse, error)
	// ListUsers returns all registered users.
	ListUsers(context.Context, *emptypb.Empty) (*ListUsersResponse, error)
	// GetNodePublicKey returns the node's Ed25519 public key.
	// Agents call this once during onboarding and cache the result.
	// Use the returned key to verify X-Postbox-Signature-Ed25519 headers on
	// incoming webhook POSTs.
	GetNodePublicKey(context.Context, *emptypb.Empty) (*NodePublicKeyResponse, error)
	// GetStatus returns health and capacity metrics for the local node.
	GetStatus(context.Context, *emptypb.Empty) (*StatusReport, error)
	// RemapDomain reassigns a domain to a different node (admin operation).
	RemapDomain(context.Context, *RemapDomainRequest) (*Response, error)
	// ListDomains returns all registered domains.
	ListDomains(context.Context, *emptypb.Empty) (*ListDomainsResponse, error)
	// StartSMTP starts the SMTP listener with the given config.
	// Returns FAILED_PRECONDITION if the listener is already running.
	StartSMTP(context.Context, *SMTPConfig) (*Response, error)
	// StopSMTP stops the running SMTP listener.
	// Returns FAILED_PRECONDITION if the listener is not currently running.
	StopSMTP(context.Context, *emptypb.Empty) (*Response, error)
	// GetSMTPStatus returns the current SMTP listener state.
	GetSMTPStatus(context.Context, *emptypb.Empty) (*SMTPStatus, error)
	// GetDeliveryStatus returns webhook delivery attempts for a message/recipient pair.
	// Returns NOT_FOUND if no delivery job exists.
	GetDeliveryStatus(context.Context, *GetDeliveryStatusRequest) (*DeliveryStatusResponse, error)
	// ListDeliveryFailures returns failed and dead delivery jobs.
	// Filter by recipient_id to narrow results to a specific user.
	ListDeliveryFailures(context.Context, *ListDeliveryFailuresRequest) (*ListDeliveryFailuresResponse, error)
	mustEmbedUnimplementedPostboxServiceServer()
}

// UnimplementedPostboxServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPostboxServiceServer struct{}

func (UnimplementedPostboxServiceServer) Discover(context.Context, *DiscoverRequest) (*NodeInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method Discover not implemented")
}
func (UnimplementedPostboxServiceServer) RegisterDomain(context.Context, *RegisterDomainRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterDomain not implemented")
}
func (UnimplementedPostboxServiceServer) RegisterUser(context.Context, *RegisterUserRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterUser not implemented")
}
func (UnimplementedPostboxServiceServer) GetUser(context.Context, *GetUserRequest) (*UserProfile, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedPostboxServiceServer) SearchUsers(context.Context, *SearchUsersRequest) (*SearchUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchUsers not implemented")
}
func (UnimplementedPostboxServiceServer) ListUsers(context.Context, *emptypb.Empty) (*ListUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUsers not implemented")
}
func (UnimplementedPostboxServiceServer) GetNodePublicKey(context.Context, *emptypb.Empty) (*NodePublicKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNodePublicKey not implemented")
}
func (UnimplementedPostboxServiceServer) GetStatus(context.Context, *emptypb.Empty) (*StatusReport, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedPostboxServiceServer) RemapDomain(context.Context, *RemapDomainRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method RemapDomain not implemented")
}
func (UnimplementedPostboxServiceServer) ListDomains(context.Context, *emptypb.Empty) (*ListDomainsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDomains not implemented")
}
func (UnimplementedPostboxServiceServer) StartSMTP(context.Context, *SMTPConfig) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method StartSMTP not implemented")
}
func (UnimplementedPostboxServiceServer) StopSMTP(context.Context, *emptypb.Empty) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method StopSMTP not implemented")
}
func (UnimplementedPostboxServiceServer) GetSMTPStatus(context.Context, *emptypb.Empty) (*SMTPStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSMTPStatus not implemented")
}
func (UnimplementedPostboxServiceServer) GetDeliveryStatus(context.Context, *GetDeliveryStatusRequest) (*DeliveryStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDeliveryStatus not implemented")
}
func (UnimplementedPostboxServiceServer) ListDeliveryFailures(context.Context, *ListDeliveryFailuresRequest) (*ListDeliveryFailuresResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDeliveryFailures not implemented")
}
func (UnimplementedPostboxServiceServer) mustEmbedUnimplementedPostboxServiceServer() {}
func (UnimplementedPostboxServiceServer) testEmbeddedByValue()                        {}

// UnsafePostboxServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PostboxServiceServer will
// result in compilation errors.
type UnsafePostboxServiceServer interface {
	mustEmbedUnimplementedPostboxServiceServer()
}

func RegisterPostboxServiceServer(s grpc.ServiceRegistrar, srv PostboxServiceServer) {
	// If the following call panics, it indicates UnimplementedPostboxServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PostboxService_ServiceDesc, srv)
}

func _PostboxService_Discover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostboxServiceServer).Discover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostboxService_Discover_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostboxServiceServer).Discover(ctx, req.(*DiscoverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostboxService_RegisterDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterDomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostboxServiceServer).RegisterDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostboxService_RegisterDomain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostboxServiceServer).RegisterDomain(ctx, req.(*RegisterDomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostboxService_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostboxServiceServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostboxService_RegisterUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostboxServiceServer).RegisterUser(ctx, req.(*RegisterUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostboxService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostboxServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostboxService_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostboxServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostboxService_SearchUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostboxServiceServer).SearchUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostboxService_SearchUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostboxServiceServer).SearchUsers(ctx, req.(*SearchUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostboxService_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostboxServiceServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostboxService_ListUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostboxServiceServer).ListUsers(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostboxService_GetNodePublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostboxServiceServer).GetNodePublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostboxService_GetNodePublicKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostboxServiceServer).GetNodePublicKey(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostboxService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostboxServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostboxService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostboxServiceServer).GetStatus(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostboxService_RemapDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemapDomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostboxServiceServer).RemapDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostboxService_RemapDomain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostboxServiceServer).RemapDomain(ctx, req.(*RemapDomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostboxService_ListDomains_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostboxServiceServer).ListDomains(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostboxService_ListDomains_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostboxServiceServer).ListDomains(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostboxService_StartSMTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SMTPConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostboxServiceServer).StartSMTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostboxService_StartSMTP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostboxServiceServer).StartSMTP(ctx, req.(*SMTPConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostboxService_StopSMTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostboxServiceServer).StopSMTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostboxService_StopSMTP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostboxServiceServer).StopSMTP(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostboxService_GetSMTPStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostboxServiceServer).GetSMTPStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostboxService_GetSMTPStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostboxServiceServer).GetSMTPStatus(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostboxService_GetDeliveryStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeliveryStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostboxServiceServer).GetDeliveryStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostboxService_GetDeliveryStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostboxServiceServer).GetDeliveryStatus(ctx, req.(*GetDeliveryStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostboxService_ListDeliveryFailures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDeliveryFailuresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostboxServiceServer).ListDeliveryFailures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostboxService_ListDeliveryFailures_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostboxServiceServer).ListDeliveryFailures(ctx, req.(*ListDeliveryFailuresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PostboxService_ServiceDesc is the grpc.ServiceDesc for PostboxService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PostboxService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "postbox.v1.PostboxService",
	HandlerType: (*PostboxServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Discover",
			Handler:    _PostboxService_Discover_Handler,
		},
		{
			MethodName: "RegisterDomain",
			Handler:    _PostboxService_RegisterDomain_Handler,
		},
		{
			MethodName: "RegisterUser",
			Handler:    _PostboxService_RegisterUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _PostboxService_GetUser_Handler,
		},
		{
			MethodName: "SearchUsers",
			Handler:    _PostboxService_SearchUsers_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _PostboxService_ListUsers_Handler,
		},
		{
			MethodName: "GetNodePublicKey",
			Handler:    _PostboxService_GetNodePublicKey_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _PostboxService_GetStatus_Handler,
		},
		{
			MethodName: "RemapDomain",
			Handler:    _PostboxService_RemapDomain_Handler,
		},
		{
			MethodName: "ListDomains",
			Handler:    _PostboxService_ListDomains_Handler,
		},
		{
			MethodName: "StartSMTP",
			Handler:    _PostboxService_StartSMTP_Handler,
		},
		{
			MethodName: "StopSMTP",
			Handler:    _PostboxService_StopSMTP_Handler,
		},
		{
			MethodName: "GetSMTPStatus",
			Handler:    _PostboxService_GetSMTPStatus_Handler,
		},
		{
			MethodName: "GetDeliveryStatus",
			Handler:    _PostboxService_GetDeliveryStatus_Handler,
		},
		{
			MethodName: "ListDeliveryFailures",
			Handler:    _PostboxService_ListDeliveryFailures_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "postbox/v1/postbox.proto",
}
